export const weather_codes = {
  0: {
    class: "clear",
    description: "Clear Sky",
  },
  1: {
    class: "clear",
    description: "Mainly Clear",
  },
  2: {
    class: "clouds",
    description: "Partly Cloudy",
  },
  3: { class: "clouds", description: "Overcast" },
  45: { class: "fog", description: "Fog" },
  48: { class: "fog", description: "Rime Fog" },
  51: { class: "rain", description: "Light Drizzle" },
  53: { class: "rain", description: "Moderate Drizzle" },
  55: { class: "rain", description: "Heavy Drizzle" },
  56: { class: "rain", description: "Light Freezing Drizzle" },
  57: { class: "rain", description: "Dense Freezing Drizzle" },
  61: { class: "rain", description: "Slight Rain" },
  63: { class: "rain", description: "Moderate Rain" },
  65: { class: "rain", description: "Heavy Rain" },
  66: { class: "rain", description: "Light Freezing Rain" },
  67: { class: "rain", description: "Heavy Freezing Rain" },
  71: { class: "snow", description: "Slight snowfall" },
  73: { class: "snow", description: "Moderate snowfall" },
  75: {
    class: "snow",
    description: "Heavy snowfall",
  },
  77: { class: "snow", description: "Snow Grains" },
  80: { class: "rain", description: "Slight Rain Showers" },
  81: { class: "rain", description: "Moderate Rain Showers" },
  82: { class: "rain", description: "Violent Rain Showers" },
  85: { class: "snow", description: "Light Snow Showers" },
  86: { class: "snow", description: "Heavy Snow Showers" },
  95: { class: "thunderstorm", description: "Thunderstorm" },
  96: { class: "hail", description: "Slight Hailstorm" },
  99: { class: "hail", description: "Heavy Hailstorm" },
};
